name: hermes_store
description: A new Flutter project.



publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  percent_indicator: ^4.0.0
  font_awesome_flutter: ^10.1.0

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true
  assets:
    - assets/books.json
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
        - asset: fonts/Tajawal-Medium.ttf
          weight: 600
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700

