List<dynamic> books = [
  {
    "id": 1,
    "title": "البحث عن الزمن المفقود ",
    "author": "مارسيل بروست",
    "translator": "زيد غنام",
    "language": "Bulgarian",
    "cover": "assets/images/book1.jpg",
    "number_of_pages": 181,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 30.04,
  },
  {
    "id": 2,
    "title": "Shot in the Heart",
    "author": "Feliza Gauch",
    "translator": "Loren MacMillan",
    "language": "Hungarian",
    "cover": "assets/images/book2.png",
    "number_of_pages": 122,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 7.38,
  },
  {
    "id": 3,
    "title": "Macabre",
    "author": "Carny Lismer",
    "translator": "Arturo Loakes",
    "language": "Kashmiri",
    "cover": "assets/images/book3.jpg",
    "number_of_pages": 482,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 30.46,
  },
  {
    "id": 4,
    "title": "The Sweet Ride",
    "author": "Rowland Titford",
    "translator": "Elle Hundall",
    "language": "Burmese",
    "cover": "assets/images/book4.jpg",
    "number_of_pages": 546,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 39.45,
  },
  {
    "id": 5,
    "title": "Lesson Plan ",
    "author": "Avigdor Alps",
    "translator": "Phil Espine",
    "language": "Dutch",
    "cover": "assets/images/book5.jpg",
    "number_of_pages": 1206,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 2.13,
  },
  {
    "id": 6,
    "title": "My Father's Glory (La gloire de mon père)",
    "author": "Konstantine Lorente",
    "translator": "Harbert Elcock",
    "language": "Kannada",
    "cover": "assets/images/book6.png",
    "number_of_pages": 565,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 13.37,
  },
  {
    "id": 7,
    "title": "Munich",
    "author": "Ethelred Snowden",
    "translator": "Markus Blundon",
    "language": "Papiamento",
    "cover": "assets/images/book7.jpg",
    "number_of_pages": 600,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 37.04,
  },
  {
    "id": 8,
    "title": "Somebody Up There Likes Me",
    "author": "Tonie Frostdicke",
    "translator": "Feodora Allmen",
    "language": "Persian",
    "cover": "assets/images/book8.jpg",
    "number_of_pages": 232,
    "book_category": [
      "رومنسي",
      "أكشن",
      "مغامرة",
      "كوميدي",
      "سباسي",
      "خيال علمي",
    ],
    "book_house": "دار البقاء",
    "price": 17.58,
  },
];
